### ISSUE TITLE
Exercise: Summarizing penguins

### ISSUE THREAD

**Issue by monacoba** [tidy-MN/R-camp-penguins#1]
https://tidy-mn.github.io/R-camp-penguins/page/exercise/describe_penguin_populations.html

### Mark Lee
What dataset am I supposed to use for the “summarizing penguins” exercise? I can’t find that in the instructions.

Exercise | Frustration   Level | Enjoyability | Usefulness | Time to   complete | Learn   anything?
-- | -- | -- | -- | -- | --
Summarizing   penguins | 4/10 I did   not know which dataset I was supposed to use at first | 6/10 cool   data set, the tasks were a bit repetitive | 7/10 group_by   and summarize are great, could perhaps also use mutate. For example, to   convert bill length for mm to cm. | About 30   minutes, but that is including the time it took to find out which data to   use. | I learned   about palmerpenguins and I discovered that I could group by more than one   column at a time. (I probably learned this at one point, but almost never   need it, so I was not immediately sure how to do it.)

### LJ Panas
There is a shift in the datasets in the questions(or there could be as most can be answered without the raw except culmen). You might specify the datasets leading in to the questions since this may be frustrating to some. Disregard comment if you’re only planning to use the raw dataset from the palmerpenguins package for these exercises.

**Comment by monacoba** [comment]
Added additional comments from Mark!

**Comment by ajstamm** [comment]
I addressed both of these in my updated Rmd file.

**Comment by dKvale** [comment]
Completed.
