### ISSUE TITLE
JOINS

### ISSUE THREAD

**Issue by monacoba** [tidy-MN/R-camp-penguins#5]
### LJ Panas
Instruct them to look at the different columns in a little detail. 
Example: if you do str, the dates are all plausible sans any other information to the researcher.  
 `str(biscoe$date)`
`str(dream$date)`

Other approaches may provider a little more information to parse out what the dates are doing. 
`df %>% select(date) %>% print(n = 50)`
`df %>% glimpse %>% select() %>% print(n=50)`
`head(df$date, 50)`

You point out the dates issue as part of the exercise but maybe make it hidden in a hint or as a question when moving on to the actual recode (with the code also in the hint) to encourage working through data exploration in R and then look at the explanation.

Torg is already a date, so it does not require a conversion. 
The current draft also is recoding island to be the date that is already a date. 
`torg <- torg %>%`
 `mutate(island = ymd(date))`

Given that this is working within tidy, should `rbind()` be `bind_rows()`?
Rbind still returns a tibble, so either is fine. Just asking for consistency purposes.  

I assume you’ll have a longer discussion of joins before this, so an explainer will not be necessary as to why and when various approaches are of use. 

Thoughts and findings. Take anything of use and feel free to ignore the rest. 😊

**Comment by dKvale** [comment]
Complete
