### ISSUE TITLE
2.2 - ifelse and casewhen

### ISSUE THREAD

**Issue by dKvale** [tidy-MN/R-camp-penguins#6]
@monacoba - Ready for primetime: https://tidy-mn.github.io/R-camp-slides/day2/02-2-Forks-in-the-road.html#1

If you can manage to play this lightning sound on another screen when you push the big play button that'd be fun: https://www.youtube.com/watch?v=0zLIPEjoRyg

Here's some ideas for the live demo portion: https://tidy-mn.github.io/R-camp-penguins/page/day2.html#forks-in-the-road-if_else-and-case_when

**Comment by monacoba** [comment]
Video done! There's a moment where the trim function in stream did me dirty
but otherwise I'm pretty happy with it

**Comment by dKvale** [comment]
:clap:  :clap: :monkey:
