### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by dKvale** [tidy-MN/R-camp-penguins#9]
Add Day 6 link to navbar Training drop-down menu

**Comment by ramnaresh8** [comment]
Would love to work on it. However, I see that the page for the day 6 link is not available. 
I tried hitting the link https://tidy-mn.github.io/R-camp-penguins/page/day6.html which is similar to other days from 1 to 5. 
Can you find the link?

**Comment by dKvale** [comment]
Not needed
